export const EDITOR_KEYS = [
  "basemodels",
  "samplers",
  "schedulers",
  "categories",
  "checkpointtypes",
  "modelfileformats",
  "modeltypes",
  "modelresolutions",
  "lyric_genres",
  "lyric_languages",
  "lyric_keyscales",
  "lyric_diffusionmodels",
  "lyric_diffusionmodelweightdtypes",
  "lyric_cliploaders",
  "lyric_cliploadertypes",
  "lyric_samplernames",
  "lyric_samplerschedulers",
];

export const defaultFormData = {
  id: null,
  title: "",
  favourite: false,
  image: "",
  positive: "",
  negative: "",
  stylePrompt: "",
  refinerPrompt: "",
  width: 0,
  height: 0,
  modelresolution: "",
  steps: 30,
  cfgScale: 7.0,
  seed: -1,
  sampler: "DPM++ 2M Karras",
  scheduler: "Simple",
  basemodel: "SDXL_1.0.safetensors",
  checkpointtype: "Merged",
  modelfileformat: "Safe Tensor",
  modeltype: "Checkpoint",
  vae: "Automatic",
  clipSkip: 2,
  denoise: 0.7,
  addNoise: true,
  startStep: 0,
  endStep: 100,
  processType: "Text to Image",
  usedPromptType: "SDXL",
  category: "Character Design",
  subCategory: "",
  comment: "",
  modelUrl: "",
  promptDate: new Date().toISOString().split("T")[0],
};

export const defaultSongForm = {
  id: null,
  type: "song",
  title: "",
  favourite: false,
  // Tab 01
  genre: "",
  prompt: "",
  lyrics: "",
  tags: "",
  // Tab 02
  duration: 0,
  bpm: 120,
  timeSignature: 4,
  language: "",
  keyscale: "",
  cfgScale: 7.0,
  temperature: 1.0,
  topP: 0.9,
  topK: 50,
  minP: 0.05,
  // Tab 03
  diffusionModel: "",
  diffusionModelWeightDtype: "",
  clipLoader01: "",
  clipLoader02: "",
  clipLoaderType: "",
  seed: -1,
  modelShift: 0.0,
  // Tab 04
  samplerSteps: 20,
  samplerCfg: 7.0,
  samplerName: "",
  samplerScheduler: "",
  samplerDenoise: 1.0,
  comment: "",
  promptDate: new Date().toISOString().split("T")[0],
};
